package defs

const (
	SQLInsertInto = "INSERT INTO "
	SQLValues     = " VALUES "
	SQLReturning  = " RETURNING "
	SQLUpdate     = "UPDATE "
	SQLSet        = " SET "
	SQLSelect     = "SELECT "
	SQLFrom       = " FROM "
	SQLWhere      = " WHERE "
	SQLDelete     = "DELETE FROM "
	SQLAnd        = " AND "
	SQLEquals     = " = "
	SQLCommaSpace = ", "
	SQLSpace      = " "
	SQLOpenParen  = " ( "
	SQLCloseParen = " ) "
	SQLIn         = " IN "
	SQLOrderBy    = " ORDER BY "
	SQLAsc        = " ASC"
	SQLDesc       = " DESC"
	SQLOr         = " OR "
	SQLNot        = "NOT "
	SQLLike       = " LIKE "
	SQLILike      = " ILIKE "
	SQLIsNull     = " IS NULL"
	SQLIsNotNull  = " IS NOT NULL"

	SQLInnerJoin = " INNER JOIN "
	SQLLeftJoin  = " LEFT JOIN "
	SQLRightJoin = " RIGHT JOIN "
	SQLJoin      = " JOIN "
	SQLOn        = " ON "
	SQLAs        = " AS "
)
