package defs

const (
	SQLInsertInto = "INSERT INTO "
	SQLValues     = "\nVALUES "
	SQLReturning  = "\nRETURNING "
	SQLUpdate     = "UPDATE "
	SQLSet        = "\nSET "
	SQLSelect     = "SELECT "
	SQLFrom       = " FROM "
	SQLWhere      = "\nWHERE "
	SQLDelete     = "DELETE FROM "
	SQLAnd        = " AND "
	SQLEquals     = " = "
	SQLCommaSpace = ", "
	SQLSpace      = " "
	SQLOpenParen  = " ( "
	SQLCloseParen = " ) "
	SQLIn         = " IN "
	SQLOrderBy    = "\nORDER BY "
	SQLAsc        = " ASC"
	SQLDesc       = " DESC"
	SQLOr         = " OR "
	SQLNot        = "NOT "
	SQLLike       = " LIKE "
	SQLILike      = " ILIKE "
	SQLIsNull     = " IS NULL"
	SQLIsNotNull  = " IS NOT NULL"

	SQLInnerJoin = " INNER JOIN "
	SQLLeftJoin  = " LEFT JOIN "
	SQLRightJoin = " RIGHT JOIN "
	SQLJoin      = " JOIN "
	SQLOn        = " ON "
	SQLAs        = " AS "
)
