package field_info

import (
	"cmp"
	"errors"
	"reflect"
	"slices"
	"strings"

	"github.com/mirrorru/qqm/meta"
)

var tagName = "qqm"

const (
	keyPK      = "pk"      // Primary key
	keyRO      = "ro"      // selecting only (read only)
	keyAuto    = "auto"    // Autogenerated (no inserting)
	keyEmbed   = "embed"   // struct embedding
	keyOmit    = "omit"    // Full ignore for select/insert/update
	keyColName = "col="    // Column name
	keyPrefix  = "prefix=" // Subcolumns name prefix
	keyRef     = "ref="    // FK reference

	//keyCreate = "create" // selecting and inserting only
	//keyUpdate = "update"  // selecting and updating only
)
const keySeparator = ";"

type FieldFlags struct {
	IsPK     bool // keyPK
	ReadOnly bool // keyRO
	AutoGen  bool // keyAuto
	Embed    bool
	ColName  string // keyColName
	Prefix   string // keyPrefix
	Ref      string
}

func (f *FieldFlags) Merge(parent FieldFlags) {
	f.IsPK = f.IsPK || parent.IsPK
	f.ReadOnly = f.ReadOnly || parent.ReadOnly
	f.AutoGen = f.AutoGen || parent.AutoGen
	// no Embed merging
	// no ColName merging
	f.Prefix = parent.Prefix + f.Prefix
	// no Ref merging
}

func parseTag(tag string) (result FieldFlags, ok bool) {
	isKey := func(key, val string) bool {
		l := len(key)
		return len(val) >= l && val[:l] == key
	}
	keys := strings.Split(tag, keySeparator)
	for _, key := range keys {
		switch {
		case key == keyPK:
			result.IsPK = true
		case key == keyRO:
			result.IsPK = true
		case key == keyAuto:
			result.AutoGen = true
		case key == keyEmbed:
			result.Embed = true
		case isKey(keyOmit, key):
			return result, false
		case isKey(keyColName, key):
			result.ColName = key[len(keyColName):]
		case isKey(keyPrefix, key):
			result.Prefix = key[len(keyPrefix):]
		case isKey(keyRef, key):
			result.Ref = key[len(keyRef):]
		}
	}
	return result, true
}

type TableField struct {
	Index   []int
	Path    []string
	SQLName string
	Flags   FieldFlags
}
type TableFields []TableField

// CollectTableFields -
func CollectTableFields(t reflect.Type) (TableFields, error) {
	if t.Kind() != reflect.Struct {
		return nil, errors.New("varPtr must be a pointer to struct")
	}
	result := make([]TableField, 0, t.NumField())
	for idx := range t.NumField() {
		newFields := collectFieldInfo(t.Field(idx), FieldFlags{})
		result = append(result, newFields...)
	}
	return result, nil
}

func collectFieldInfo(fld reflect.StructField, parentFlags FieldFlags) []TableField {
	if !fld.IsExported() {
		return nil
	}

	flags, processable := parseTag(fld.Tag.Get(tagName))
	if !processable {
		return nil
	}

	if fld.Type.Kind() == reflect.Struct && (fld.Anonymous || flags.Embed) {
		result := make([]TableField, 0, fld.Type.NumField())
		// Поле-структура требует "распаковки" на отдельные поля
		subField := fld.Type

		for i := range subField.NumField() {
			subResult := collectFieldInfo(subField.Field(i), flags)
			for idx := range subResult {
				subResult[idx].Index = append(fld.Index, subResult[idx].Index...)
				subResult[idx].Path = slices.Insert(subResult[idx].Path, 0, fld.Name)
			}
			result = append(result, subResult...)
		}
		return result
	}

	fldInfo := TableField{
		Index:   fld.Index,
		Path:    []string{fld.Name},
		Flags:   flags,
		SQLName: flags.Prefix + cmp.Or(flags.ColName, meta.ToSnakeCase(fld.Name)),
	}

	return []TableField{fldInfo}
}

func (tf *FieldFlags) CanInsert() bool {
	return !tf.ReadOnly && !tf.AutoGen
}

func (tf *FieldFlags) CanUpdate() bool {
	return !tf.ReadOnly && !tf.IsPK
}

func (tf *FieldFlags) CanSelect() bool {
	return true
}

func (tfs TableFields) InsertingColsIdx() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.CanInsert() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) UpdatingColsIdx() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.CanUpdate() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) SelectingColsIdx() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.CanSelect() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) PKColsIdx() []int {
	result := make([]int, 0, 2)
	for idx := range tfs {
		if tfs[idx].Flags.IsPK {
			result = append(result, idx)
		}
	}
	return result
}
