package field_info

import (
	"cmp"
	"errors"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/mirrorru/qqm/meta"
)

var tagName = "tbl"

const (
	keyPK      = "pk"      // Primary key
	keyRO      = "ro"      // selecting only (read only)
	keyAuto    = "auto"    // Autogenerated (no inserting)
	keyEmbed   = "embed"   // struct embedding
	keyOmit    = "omit"    // Full field ignore
	keyColName = "col="    // Column name
	keyInsert  = "ins"     // force field inserting
	keyUpdate  = "upd"     // force field updating
	keyHide    = "rskip"   // skip field on selecting
	keyPrefix  = "prefix=" // Subcolumns name prefix
	keyRef     = "ref="    // FK reference
	keySort    = "sort="   // Sort <position>[,desc]
)
const keySeparator = ";"
const inKeySeparator = ","

type FieldFlags struct {
	IsPK         bool // keyPK
	ReadOnly     bool // keyRO
	AutoGen      bool // keyAuto
	Embed        bool
	ForceUpdate  bool
	ForceInsert  bool
	SkipReading  bool
	ColName      string // keyColName
	Prefix       string // keyPrefix
	Ref          string
	SortPos      int
	SortBackward bool
}

func (f *FieldFlags) Merge(parent FieldFlags) {
	f.IsPK = f.IsPK || parent.IsPK
	f.ReadOnly = f.ReadOnly || parent.ReadOnly
	f.AutoGen = f.AutoGen || parent.AutoGen
	f.ForceUpdate = f.ForceUpdate || parent.ForceUpdate
	f.ForceInsert = f.ForceInsert || parent.ForceInsert
	f.SkipReading = f.SkipReading || parent.SkipReading
	// no Embed merging
	// no ColName merging
	f.Prefix = parent.Prefix + f.Prefix
	// no Ref merging
	if f.SortPos == 0 {
		f.SortPos = parent.SortPos
		f.SortBackward = parent.SortBackward
	}
}

func parseTag(tag string) (result FieldFlags, ok bool) {
	isKey := func(key, val string) bool {
		l := len(key)
		return len(val) >= l && val[:l] == key
	}
	keys := strings.Split(tag, keySeparator)
	for _, key := range keys {
		switch {
		case key == keyPK:
			result.IsPK = true
		case key == keyRO:
			result.ReadOnly = true
		case key == keyAuto:
			result.AutoGen = true
		case key == keyEmbed:
			result.Embed = true
		case isKey(keyOmit, key):
			return result, false
		case key == keyInsert:
			result.ForceInsert = true
		case key == keyUpdate:
			result.ForceUpdate = true
		case key == keyHide:
			result.SkipReading = true
		case isKey(keyColName, key):
			result.ColName = key[len(keyColName):]
		case isKey(keyPrefix, key):
			result.Prefix = key[len(keyPrefix):]
		case isKey(keyRef, key):
			result.Ref = key[len(keyRef):]
		case isKey(keySort, key):
			s := strings.ToLower(key[len(keySort):])
			ss := strings.SplitN(s, inKeySeparator, 2)
			result.SortPos, _ = strconv.Atoi(ss[0])
			if len(ss) > 1 {
				result.SortBackward = ss[1] == "desc"
			}
		}
	}
	return result, true
}

type TableField struct {
	Index   []int
	Path    []string
	SQLName string
	Flags   FieldFlags
}
type TableFields []TableField

// CollectTableFields -
func CollectTableFields(t reflect.Type) (TableFields, error) {
	if t.Kind() != reflect.Struct {
		return nil, errors.New("varPtr must be a pointer to struct")
	}
	result := make([]TableField, 0, t.NumField())
	for idx := range t.NumField() {
		newFields := collectFieldInfo(t.Field(idx), FieldFlags{})
		result = append(result, newFields...)
	}
	return result, nil
}

func collectFieldInfo(fld reflect.StructField, parentFlags FieldFlags) []TableField {
	if !fld.IsExported() {
		return nil
	}

	flags, processable := parseTag(fld.Tag.Get(tagName))
	if !processable {
		return nil
	}

	if fld.Type.Kind() == reflect.Struct && (fld.Anonymous || flags.Embed) {
		result := make([]TableField, 0, fld.Type.NumField())
		// Поле-структура требует "распаковки" на отдельные поля
		subField := fld.Type

		for i := range subField.NumField() {
			subResult := collectFieldInfo(subField.Field(i), flags)
			for idx := range subResult {
				subResult[idx].Index = append(fld.Index, subResult[idx].Index...)
				subResult[idx].Path = slices.Insert(subResult[idx].Path, 0, fld.Name)
			}
			result = append(result, subResult...)
		}
		return result
	}

	fldInfo := TableField{
		Index:   fld.Index,
		Path:    []string{fld.Name},
		Flags:   flags,
		SQLName: flags.Prefix + cmp.Or(flags.ColName, meta.ToSnakeCase(fld.Name)),
	}

	return []TableField{fldInfo}
}

func (tf *FieldFlags) canInsert() bool {
	return tf.ForceInsert || !tf.ReadOnly && !tf.AutoGen
}

func (tf *FieldFlags) canUpdate() bool {
	return tf.ForceUpdate || !tf.ReadOnly && !tf.IsPK
}

func (tf *FieldFlags) canSelect() bool {
	return !tf.SkipReading
}

func (tfs TableFields) insertingCols() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.canInsert() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) updatingCols() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.canUpdate() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) selectingCols() []int {
	result := make([]int, 0, len(tfs))
	for idx := range tfs {
		if tfs[idx].Flags.canSelect() {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) pkCols() []int {
	result := make([]int, 0, 2)
	for idx := range tfs {
		if tfs[idx].Flags.IsPK {
			result = append(result, idx)
		}
	}
	return result
}

func (tfs TableFields) sortingCols() []int {
	result := make([]int, 0, len(tfs)/2)
	for idx := range tfs {
		if tfs[idx].Flags.SortPos != 0 {
			result = append(result, idx)
		}
	}
	slices.SortStableFunc(result, func(a, b int) int {
		return tfs[a].Flags.SortPos - tfs[b].Flags.SortPos
	})

	return result
}

func (tfs TableFields) refCols() []int {
	result := make([]int, 0, 2)
	for idx := range tfs {
		if tfs[idx].Flags.Ref != "" {
			result = append(result, idx)
		}
	}
	return result
}

type fieldsIndexes struct {
	PKCols      []int
	SelectCols  []int
	InsertCols  []int
	UpdateCols  []int
	SortingCols []int
	RefCols     []int
}

func (tfs TableFields) allIndexes() fieldsIndexes {
	return fieldsIndexes{
		PKCols:      tfs.pkCols(),
		SelectCols:  tfs.selectingCols(),
		InsertCols:  tfs.insertingCols(),
		UpdateCols:  tfs.updatingCols(),
		SortingCols: tfs.sortingCols(),
		RefCols:     tfs.refCols(),
	}
}
